Algoritmo "Exercicio2"

var
nome,endereco,telefone,cidade,cep:caractere
Inicio
escreva("Nome: ")
leia(nome)
escreva("endereco: ")
leia(endereco)
escreva("telefone: ")
leia(telefone)
escreva("cidade: ")
leia(cidade)
escreva("cep: ")
leia(cep)
escreva("-----------------------------------")
escreval("Nome: ", nome, " Endereço: ", endereco)
escreval(" Telefone: ", telefone, " Cidade: ", cidade, " Cep: ", cep)
Fimalgoritmo