Algoritmo "Questao2"
// Grace Irene de Oliveira Silveira
//Turma:847
//Materia: Algoritmo 1.
//Unicarioca Meier 2


//Questão 2) Escreva um programa que leia uma temperatura em graus Fahrenheit
//e a transforme em Celsius. Fórmula: C = (F-32)/1,8. (Valor 0,1 ponto)
Var
C:real
F:inteiro

Inicio
Escreval("Digite o Fahrenheit")
leia(F)

C<-(F-32)/1.8

Escreval("-----------------------------")
Escreval("Celsios: ", C)

Fimalgoritmo